search:
  BackfillEnabled: false
  Can:
    Delete: true
    Modify: true
    Share: true
  DebugEvent: null
  DebugMode: false
  DebugOutput: null
  Description: Web Application Tampering
  Disabled: false
  Duration: -300
  ErrorHistory: null
  Flow: ''
  FlowNodeResults: null
  GUID: 9a12455a-aa14-4399-b16e-58083107b45e
  Global: false
  Groups:
  - 1
  ID: 343622226
  Labels:
  - Webserver
  - WebApplication
  - Medium
  - kit/io.gravwell.syslog
  LastError: ''
  LastRun: '2025-07-12T20:20:00-07:00'
  LastRunDuration: 1462595580
  LastSearchIDs:
  - '51982231732'
  Name: Web Application Tampering
  OneShot: false
  Owner: 1
  PersistentMaps: {}
  Schedule: '*/5 * * * *'
  ScheduledType: search
  Script: ''
  ScriptLanguage: 0
  SearchReference: 00000000-0000-0000-0000-000000000000
  SearchSinceLastRun: false
  SearchString: 'tag=syslog src "10.128.40.2" | syslog Message | words "404" | length
    | stats count(length) as total | eval (total >= 3) '
  Synced: false
  TimeframeOffset: 0
  Timezone: ''
  Updated: '2025-06-21T05:14:34.451769115-07:00'
  WriteAccess:
    GIDs: []
    Global: false
